### ISSUE TITLE
Reveal the widget only when the mouse reaches the screen's right (or left) edge

### ISSUE THREAD

**Issue by varemenos** [xndcn/symbols-tree-view#11]

**Comment by xndcn** [comment]
@varemenos Good idea! Thanks, I will try to implement it.

**Comment by xndcn** [comment]
@varemenos Please upgrade and checked option `Auto Hide`.
I wish you like it.

**Comment by dbpolito** [comment]
Works great, thanks for this...

**Comment by varemenos** [comment]
I'm gonna close this, if anyone has issues please post it here so @xndcn can reopen it
