### ISSUE TITLE
Updated to 0.13 and no more working

### ISSUE THREAD

**Issue by kavitama** [xndcn/symbols-tree-view#111]
After updating to 0.13 no more working.
How to get to a previos version ????

**Comment by wanyikang** [comment]
just uninstall in the atom, and then use apm to install a specifical version, I do it like this:
apm install symbols-tree-view@0.12.0

**Comment by kavitama** [comment]
Can it be done also in Windows 7 ?

**Comment by kavitama** [comment]
Great! it worked
Big thank you !!!!!!

**Comment by wanyikang** [comment]
yes, but you must make apm work on you win7, that's some kind of work of adding path to you windows environmental variable. apm is working on my win10 comand line, so does python~
![qq 20160531092314](https://cloud.githubusercontent.com/assets/5843919/15660616/50eb1f0c-2711-11e6-9a73-ffbb51141dfe.png)

**Comment by xndcn** [comment]
Sorry, please see #109
