### ISSUE TITLE
Function only

### ISSUE THREAD

**Issue by xyluet** [xndcn/symbols-tree-view#113]
Can i make this package to show function only by default ? or any setting that i can choose function only, etc

Thank you

**Comment by haryshwaran** [comment]
The lazy and also the quickest way without editing the code is to edit the ~/.atom/packages/symbols-tree-view/styles/symbols-tree-view.less to hide the variables. You may have to add it again on updates until the feature is added.

`span.icon-variable{
  display: none !important;
}
`
