### ISSUE TITLE
Incorrectly matches keywords in docblock (eg. function)

### ISSUE THREAD

**Issue by ol1s** [xndcn/symbols-tree-view#116]
If a docblock contains keywords (eg. `function`) then symbols-tree-view is bookmarking this incorrectly as a symbol.

For example:

```
`/**
 * @param string $validation_function **function that** will validate the user input
 */`
```

is adding the following bookmark to the tree view:

```
f(x) that
```

**Comment by attheshow** [comment]
Same issue here.

```
/**
 * Helper function to build author link
 */
```

is adding a bookmark that simply says

> to
