### ISSUE TITLE
Regex errors and disorganized entries

### ISSUE THREAD

**Issue by batjko** [xndcn/symbols-tree-view#13]
Hi,

First of all, I'm looking forward to using this package, it's a god-send!

But I'm getting these two issues, which may or may not be related to each other (let me know if I should open two separate issues instead):

1. I get a number of sections that are literal regex expressions (or parts thereof) with ctags errors nested in them.

2. I don't understand the sections I highlighted in blue: They seem to show different content, i.e. package, vars, functions etc, which is good, but they are weirdly disjointed.

Now, I could see how the second issue might be a consequence of the first, but I let you be the judge.
![image](https://cloud.githubusercontent.com/assets/7287076/6388651/3d70e1ce-bd94-11e4-8721-8c1894d7f221.png)

Thanks!

**Comment by xndcn** [comment]
@batjko Thank you. There seems something wrong with `ctags`, which is used to generate symbols.
Does it occur everytime, or only in this source file? Would you mind to copy your source file here?

**Comment by batjko** [comment]
Sorry, the source file is protected by my employer. But it's a standard java file and it happens with all of the files I tried, including Java, C#, SQL.

As you can see I'm on Windows (8.1 64bit), so maybe it's an issue with ctags-win32 specifically?

My atom version is 182.

**Comment by xndcn** [comment]
@batjko OK, I think you are right, it may be the problem of incompatibility between 32bit and 64bit...
I will try to reproduce this problem and fix it.

**Comment by batjko** [comment]
If I can help in any way, let me know. 
I'm not sure how to get at the full ctags error since it's cut off by the fixed panel width.

**Comment by xndcn** [comment]
@batjko Thanks, you can get the ctags output in `cmd` by running:
`ctags-win32 --fields=KsS`

**Comment by batjko** [comment]
Ah! Maybe I'm particularly dense today, but does your package actually require ctags to be installed separately? Because I dont.

**Comment by xndcn** [comment]
@batjko No need, there is `ctags-win32` in directory `vendor/`
https://github.com/xndcn/symbols-tree-view/tree/master/vendor

**Comment by batjko** [comment]
Ok found it. I just ran that command against one of my java files and I get no output:
![image](https://cloud.githubusercontent.com/assets/7287076/6392040/6d618954-bdb4-11e4-92a0-e29d87bbb2cd.png)

**Comment by xndcn** [comment]
@batjko Sorry... It should be
`path/to/ctags-win32 --fields=KsS -nf - foo.bar`

**Comment by batjko** [comment]
Alright, here's the output from that:

    `ctags-win32 --fields=KsS -nf - [filepath]`

    CONFONEEDED     [filepath]     49;"    field   class:[myawesomeclass]
    [myawesomeclass]  [filepath]     45;"    class
    UTIEXTRACT      [filepath]     48;"    field   class:[myawesomeclass]
    UTIGENERATOR    [filepath]     47;"    field   class:[myawesomeclass]
    doit    [filepath]     70;"    method  class:[myawesomeclass]    signature: (IContainerContext context)
    e       [filepath]     52;"    field   class:[myawesomeclass]
    execute [filepath]     54;"    method  class:[myawesomeclass]    signature (IContainerContext context)
    recipients      [filepath]     50;"    field   class:[myawesomeclass]
    set_UTI_Extract_Flag    [filepath]     166;"   method  class:[myawesomeclass] signature:(Table tblArgt, Transaction trn, int iFromStatus, int iToStatus)
    uti     [filepath]     34;"    package

So, I'm guessing it works fine when run on the command line, as there weren't any errors.

**Comment by xndcn** [comment]
@batjko I see, if you run `ctags --options=..\lib\.ctags --fields=KsS -nf - [filepath]` then some warning will occur... There seems some wrong in the file `lib\.ctags`, I'm checking it.

**Comment by xndcn** [comment]
Fix in cd179a1a6056b2accd98919a4c4c3dde8552dc3e

**Comment by xndcn** [comment]
@batjko Please update to new version and check it again, thanks!

**Comment by batjko** [comment]
Yup, working perfectly now!
Thanks for the quick turnaround @xndcn!
