### ISSUE TITLE
(Java) Redundant entries for the class declaration

### ISSUE THREAD

**Issue by batjko** [xndcn/symbols-tree-view#14]
Very minor weird thing here:

Essentially, it shows me the class declaration and if I click on it, it leads me there correctly (green).
But below it gives me a second line for the class declaration under which it then starts the symbol tree. And if I click on that one, it leads me into the middle of nowhere, somewhere before the constructor (red).

![image](https://cloud.githubusercontent.com/assets/7287076/6410194/e3af7138-be64-11e4-98e6-00c7b3800a4d.png)

*Edit:*
Actually, I just noticed that the third entry looking to be a class declaration as well, is also rogue:
![image](https://cloud.githubusercontent.com/assets/7287076/6410350/9095c838-be66-11e4-8d1d-2a1e7df8627b.png)

**Comment by xndcn** [comment]
@batjko Thanks, it's weird, and seems only happen on `Windows`... I'm still debugging

**Comment by xndcn** [comment]
@batjko I think I have found the reason... On `Windows` there is an additional `CR(\r)` at the end of a line, so `LogOutput\r` is different from `LogOutput`, and that's why there are two `LogOutput`...

**Comment by xndcn** [comment]
@batjko Please upgrade and check it again, thanks!

**Comment by batjko** [comment]
Yup, looking good:
![image](https://cloud.githubusercontent.com/assets/7287076/6425902/46720ed4-bf37-11e4-8297-ac4528f2c0a0.png)

Thanks, again!
