### ISSUE TITLE
Use Atom Docks

### ISSUE THREAD

**Issue by Yanpas** [xndcn/symbols-tree-view#168]
Atom have introduced docks in 1.17, the side pane has gained round buttons to show/hide dock. Plugin would benefit from using it

**Comment by Joouis** [comment]
@Yanpas  Hi, maybe you can try this newer plugin which used docker.

https://atom.io/packages/structure-view

![image](https://user-images.githubusercontent.com/8896124/33807908-b57adcc2-de18-11e7-9eed-a90e48f21382.png)

**Comment by Yanpas** [comment]
Looks nice, anyway I've switched to vscode
