### ISSUE TITLE
No hierarchy in the tree view panel

### ISSUE THREAD

**Issue by martin-damien** [xndcn/symbols-tree-view#17]
![capture d ecran - 02032015 - 16 44 31](https://cloud.githubusercontent.com/assets/295478/6444089/9709afd0-c0fb-11e4-9b8c-88aa1d20e3ca.png)

Hi,

As you can see I have no hierarchy in the tree view.

Do you have any idea from where it comes? (It is not the UI theme, I tyed with "Atom Dark" and had the same result).

I checked the generated code too and there is only one `<ul>` (no subtrees).

Thanks,

Damien

**Comment by genofire** [comment]
Same Problem on LaTeX with section and subsections! (Sould a make a own issue?)

**Comment by xndcn** [comment]
Sorry for that, now symbols and their relationship are generated by `ctags`. For now `ctags` can't parse `php` or `Latex` as well as `java` and `c++`, and that's why there is no hierarchy in the tree view.
I'm tring to overcome this problem by using a myself parser, but it's not easy...

**Comment by martin-damien** [comment]
Thank you for your efforts @xndcn :+1:

**Comment by lmartins** [comment]
Im having the same issue with Sass files, making the list barely usable due to multiple entries for generic symbols such as `div`, `a`, etc.

One way to get around this would be to limit the depth but surely having the list show the code nesting would be awesome.

**Comment by blipi** [comment]
The same is happening with JavaScript... CTags seems to not correctly parse modern js.
And regex rules are wrong too, it will only detect functions. Although I believe it is best like this right now, until hierarchy actually works.
Thank you for this awesome plugin!

**Comment by jzumbrun** [comment]
Until hierarchy is fixed, I think colorizing and bolding functions, etc would help.

**Comment by fuzzy76** [comment]
What ctags version do you use? Is there an upstream ticket for this?

**Comment by jeonghwan-kim** [comment]
+1

**Comment by brettz9** [comment]
+1 to hierarchy

@jzumbrun : Colorizing is being tracked in issue #26 .

@gpascualg / @fuzzy76 : https://github.com/xndcn/symbols-tree-view/blob/master/lib/.ctags has the current version. I was thinking of submitting a PR for better JavaScript tags based on merging with https://gist.github.com/tim-smart/199338  .
