### ISSUE TITLE
Auto-hide doesn't work when auto-toggle is enabled

### ISSUE THREAD

**Issue by olmokramer** [xndcn/symbols-tree-view#24]
Expected:

The `symbols-tree-view` automatically shows `5px` wide on the right side of my screen when I open a file or when Atom opens a file on startup. When I hover it with the mouse it expands to `200px` width.

Actual:

The `symbols-tree-view` automatically shows `5px` wide on the right side of my screen when I open a file or when Atom opens a file on startup. When I hover it with the mouse it <em>doesn't</em> expand to `200px` width.

Reproduction steps:

1. Enable both the `autoHide` and `autoToggle` configs.
2. Maybe reload Atom.

**Comment by dbpolito** [comment]
I can also reproduce this, if i go to settings, disable both options and enable again, fix... But i have to do everytime i open atom.

**Comment by xndcn** [comment]
Thanks! I made a mistake there that `mouseenter` and `mouseleave` events should be subscribed after `attached`. Now fixed, please update and check it again, thank you!

**Comment by olmokramer** [comment]
Awesome, thanks!

**Comment by dbpolito** [comment]
Fixed for me, thanks man.
