### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by stelek** [xndcn/symbols-tree-view#5]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
SymbolsTreeView.attach (/Users/stelek/.atom/packages/symbols-tree-view/lib/symbols-tree-view.coffee:78:13)
```

**Comment by xndcn** [comment]
@stelek Thanks, now all deprecated codes were repaired.
