### ISSUE TITLE
Change Auto Toggle name

### ISSUE THREAD

**Issue by nickvanderstel** [xndcn/symbols-tree-view#6]
I didn't realize that the Auto Toggle option would auto-open tree view. I'd suggest changing the name of the option so that the function is more obvious. 'Auto Open' would be much clearer in my opinion.

**Comment by xndcn** [comment]
2930352e242aa0808da7b67b3939c7189050f4d8

**Comment by xndcn** [comment]
Thank you for your suggestion! Sorry I may not change this option name for now, because it will make users existed settings invalid...
Therefor, I add detail description for these settings both in `Readme` and `Settings` panel.
Thank you!
