### ISSUE TITLE
Change ctags fork?

### ISSUE THREAD

**Issue by fuzzy76** [xndcn/symbols-tree-view#61]
The original ctags seems abandoned and has a lot of known, unfixed issues. Have you considered changing to a maintained fork like https://github.com/universal-ctags/ctags ?

**Comment by harmsk** [comment]
I've got a version of symbols-tree-view working with the universal-ctags. It fixes Latex parsing for me and I'm quite happy with it. I've tested it on Linux.

Would you consider a pull request? Or is there another way that you would prefer? Or do you plan on staying with exuberant ctags?

**Comment by xndcn** [comment]
@harmsk Thank you, it's very nice if you could submit a pull request.
I have to stay with the old version ctags because we need darwin/linux/win binary separately...
Maybe we should consider Linux firstly.
