### ISSUE TITLE
doesn't detect functions in python.

### ISSUE THREAD

**Issue by sayingandparsing** [xndcn/symbols-tree-view#62]
I really appreciate this navigation utility, and would cite it as one of my primary reasons for switching from sublime. However when viewing python code, it correctly displays classes and variables, but misidentifies function as variables. Since I rely on many python libraries, I'd be grateful if this could be fixed in an update.
Also, I really like the mathematical icons.

**Comment by jonobacon** [comment]
I can confirm this too.
<img width="225" alt="class" src="https://cloud.githubusercontent.com/assets/3004831/10564874/ee9f9364-7577-11e5-961f-08689411b0a5.png">

**Comment by xndcn** [comment]
Sorry for my late reply... I didn't notice this bug before...
Anyway, now fixed, please update and try it again, thank you!
